# Generated by Django 2.0.2 on 2018-03-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_test_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('contents', models.CharField(max_length=10000)),
                ('content_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Test_details',
        ),
    ]
