# Generated by Django 2.0.2 on 2018-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20180304_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('linked_varids', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='varid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acubox',
            name='content_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='acubox',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='acubox',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='variation',
            name='content_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='variation',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
