# Generated by Django 2.0.2 on 2018-03-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20180304_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='varid',
            field=models.CharField(max_length=250),
        ),
    ]
