# Generated by Django 2.0.2 on 2018-03-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180304_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='varid',
        ),
    ]
