# Generated by Django 2.0.2 on 2018-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_variation_varid'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='varid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
