# Generated by Django 2.0.2 on 2018-03-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_test_details_num_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='content_type',
            field=models.CharField(choices=[('html', 'HTML'), ('js', 'Javascript'), ('css', 'CSS')], default='html', max_length=250),
        ),
    ]
