# Generated by Django 2.0.2 on 2018-03-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20180305_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=250)),
                ('account_id', models.CharField(max_length=250)),
                ('active_tests', models.TextField()),
                ('associated_tests', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='test_details',
            name='testid',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='variation',
            name='varid',
            field=models.IntegerField(default=1000),
        ),
    ]
