# Generated by Django 2.0.2 on 2018-03-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20180305_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acubox',
            options={'verbose_name_plural': 'Acuboxes'},
        ),
        migrations.AddField(
            model_name='test_details',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.Site'),
        ),
    ]
