# Generated by Django 2.0.2 on 2018-03-08 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20180307_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_details',
            name='site',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, to='main_app.Site'),
        ),
    ]
